CREATE OR REPLACE PROCEDURE EXT.SP_PAC_MARCADO_EXTORNO_S5_TEST (IN i_file_name varchar(120))
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS

/*---------------------------------------------------------------------
    | Author: Samuel Miralles Manresa
    | Company: Inycom
    | Initial Version Date: 17/04/2026
    |----------------------------------------------------------------------
    | Procedure Purpose: Por cada póliza que aparezca en el fichero y el número de transacciones a marcar que se informará en el fichero
    |
    | Version: 0.1  SMM 20260331    Initial Version.
    | Version: 1.0  SMM 20260521    Cambio de nombre
    | Version: 2.0  SMM 20260525    Resultado en tabla temporal EXT.MARCADO_TRANSACTIONASSIGN_HIST
    | Version: 2.1  SMM 20260526    Añadir filtro Excluido Comisiones en las transacciones S.GENERICATTRIBUTE20 = 0
    |
    -----------------------------------------------------------------------
*/

BEGIN
	
	USING SQLSCRIPT_STRING AS LIBRARY;
	
	DECLARE v_id_proceso INTEGER;
	DECLARE proc_name VARCHAR2(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version VARCHAR2(10) := '2.1';
	DECLARE v_num_rows INTEGER := 0;
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_permisos_log VARCHAR(50) := EXT.LIB_GLOBAL:GET_PERMISOS_LOG();
	DECLARE v_idtenant VARCHAR(50) := EXT.LIB_GLOBAL:getTenantID();
	DECLARE v_eot DATE := EXT.LIB_CONSTANTES:v_eot;
	DECLARE v_periodseq BIGINT;
	DECLARE v_PeriodName VARCHAR(25);
	-- DECLARE v_file_name VARCHAR(250) = 'PAC_CONTEO_REQ2_';
	DECLARE v_const_processingunitseq BIGINT = 38280596832649217;
	DECLARE v_const_credito VARCHAR(50) = 'DC-O-GEN-Inspector-PrimaCorregida-998';
	DECLARE v_const_out_batch_control_load INT = EXT.LIB_CONSTANTES:CONST_OUT_BATCH_CONTROL_LOAD; --1
	DECLARE v_const_out_batch_control_ok INT := EXT.LIB_CONSTANTES:CONST_OUT_BATCH_CONTROL_OK; --2
	DECLARE v_const_out_batch_control_error INT := EXT.LIB_CONSTANTES:CONST_OUT_BATCH_CONTROL_ERROR; --3


	DECLARE TEMP_TRANSACTIONASSIGN TABLE(
	"TENANTID" VARCHAR(4),
	"STAGESALESTRANSACTIONSEQ" BIGINT ,
	"SETNUMBER" BIGINT  NOT NULL,
	"BATCHNAME" VARCHAR(90) NOT NULL,
	"FILE_IN_RECIBOS" VARCHAR(90),
	"ORDERID" VARCHAR(40),
	"LINENUMBER" BIGINT ,
	"SUBLINENUMBER" BIGINT ,
	"EVENTTYPEID" VARCHAR(40),
	"SALESTRANSACTIONSEQ" BIGINT ,
	"PAYEEID" VARCHAR(40),
	"PAYEETYPE" VARCHAR(40),
	"POSITIONNAME" VARCHAR(127),
	"TITLENAME" VARCHAR(127),
	"GENERICATTRIBUTE1" VARCHAR(255),
	"GENERICATTRIBUTE2" VARCHAR(255),
	"GENERICATTRIBUTE3" VARCHAR(255),
	"GENERICATTRIBUTE4" VARCHAR(255),
	"GENERICATTRIBUTE5" VARCHAR(255),
	"GENERICATTRIBUTE6" VARCHAR(255),
	"GENERICATTRIBUTE7" VARCHAR(255),
	"GENERICATTRIBUTE8" VARCHAR(255),
	"GENERICATTRIBUTE9" VARCHAR(255),
	"GENERICATTRIBUTE10" VARCHAR(255),
	"GENERICATTRIBUTE11" VARCHAR(255),
	"GENERICATTRIBUTE12" VARCHAR(255),
	"GENERICATTRIBUTE13" VARCHAR(255),
	"GENERICATTRIBUTE14" VARCHAR(255),
	"GENERICATTRIBUTE15" VARCHAR(255),
	"GENERICATTRIBUTE16" VARCHAR(255),
	"GENERICNUMBER1" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER1" VARCHAR(40),
	"GENERICNUMBER2" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER2" VARCHAR(40),
	"GENERICNUMBER3" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER3" VARCHAR(40),
	"GENERICNUMBER4" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER4" VARCHAR(40),
	"GENERICNUMBER5" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER5" VARCHAR(40),
	"GENERICNUMBER6" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER6" VARCHAR(40),
	"GENERICDATE1" LONGDATE ,
	"GENERICDATE2" LONGDATE ,
	"GENERICDATE3" LONGDATE ,
	"GENERICDATE4" LONGDATE ,
	"GENERICDATE5" LONGDATE ,
	"GENERICDATE6" LONGDATE ,
	"GENERICBOOLEAN1" SMALLINT ,
	"GENERICBOOLEAN2" SMALLINT ,
	"GENERICBOOLEAN3" SMALLINT ,
	"GENERICBOOLEAN4" SMALLINT ,
	"GENERICBOOLEAN5" SMALLINT ,
	"GENERICBOOLEAN6" SMALLINT 
);
	
	
	BEGIN
	
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error en procedimiento principal ' || proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																												|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, v_id_proceso, 'error');
			--v_hayError := 1;
			v_num_rows := 0;
		
		UPDATE EXT.IN_BATCH_CONTROL
			SET REJECTED_ROWS = :v_num_rows,
				STATUS = :v_const_out_batch_control_error,
				END_DATE = CURRENT_TIMESTAMP
			WHERE FILE_NAME = :i_file_name
				AND ID_PROCESO = v_id_proceso;
			
			COMMIT;
			
			-- RESIGNAL;
		END;
	
	--Inicializamos el idProceso
		SELECT EXT.ID_PROCESO.NEXTVAL INTO v_id_proceso FROM DUMMY;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Version: ' || v_version || ' - Procedure starting for filename ' || i_file_name, v_log_count, v_id_proceso, 'info');
	
		/*****************************TEST************************************/
		INSERT INTO :TEMP_TRANSACTIONASSIGN
		SELECT * FROM EXT.TRANSACTIONASSIGN WHERE EVENTTYPEID IN ('71','65');
		
		-- UPDATE :TEMP_TRANSACTIONASSIGN SET TENANTID = v_idtenant;
		
		/****************************************************************************/
		
		INSERT INTO EXT.IN_BATCH_CONTROL (ID_PROCESO, FILE_NAME, PROCEDURE_NAME, SOURCE_ROWS, STATUS, START_DATE)
		VALUES (v_id_proceso, i_file_name, proc_name, v_num_rows, v_const_out_batch_control_load, CURRENT_TIMESTAMP);
		
		SELECT TOP  1 L.PERIODSEQ, C.NAME INTO v_periodseq, v_PeriodName 
		FROM EXT.OUT_PAC_MARCADO_EXTORNO_S5_FILE_LOAD L 
		INNER JOIN CS_PERIOD C ON L.PERIODSEQ = C.PERIODSEQ;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Parametros: v_PeriodSeq: ' || v_PeriodSeq || ' - v_PeriodName: ' || v_PeriodName, v_log_count, v_id_proceso, 'info');
		
		DELETE FROM EXT.OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST WHERE PERIODSEQ = v_periodseq;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Eliminamos periodo en la tabla OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST. Filas: ' || ::ROWCOUNT, v_log_count, v_id_proceso, 'info');
		
		INSERT INTO EXT.OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST(PERIODSEQ,POSITIONNAME,CONTEO,BATCHNAME,CREATEDATE)
		SELECT PERIODSEQ,POSITIONNAME,CONTEO,i_file_name,CURRENT_TIMESTAMP FROM EXT.OUT_PAC_MARCADO_EXTORNO_S5_FILE_LOAD; 
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Cargamos periodo en la tabla OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST. Filas: ' || ::ROWCOUNT, v_log_count, v_id_proceso, 'info');
		v_num_rows = ::ROWCOUNT;
		
	
		TEMP_CREDITOS = SELECT DISTINCT C.GENERICATTRIBUTE4 POSITIONNAME
			,H.CONTEO
			,C.GENERICATTRIBUTE1 POLIZA
			,S.LINENUMBER
			,S.SUBLINENUMBER
			,E.EVENTTYPEID
			,(C.PREADJUSTEDVALUE) 
			,C.VALUE
			,SO.ORDERID
			,ROW_NUMBER() OVER (PARTITION BY C.GENERICATTRIBUTE4 ORDER BY (C.PREADJUSTEDVALUE) DESC) AS RN
			FROM CS_CREDIT C
			INNER JOIN CS_SALESTRANSACTION S ON C.SALESTRANSACTIONSEQ = S.SALESTRANSACTIONSEQ AND C.SALESORDERSEQ = S.SALESORDERSEQ AND S.PROCESSINGUNITSEQ = v_const_processingunitseq
				AND S.TENANTID = v_idtenant AND S.GENERICATTRIBUTE20 = 0
			INNER JOIN CS_SALESORDER SO ON SO.SALESORDERSEQ = S.SALESORDERSEQ AND SO.REMOVEDATE = '2200-01-01' AND SO.PROCESSINGUNITSEQ = v_const_processingunitseq
				AND SO.TENANTID = v_idtenant
			INNER JOIN CS_EVENTTYPE E ON E.DATATYPESEQ = S.EVENTTYPESEQ AND E.REMOVEDATE =  '2200-01-01' AND E.EVENTTYPEID IN ('71','65') 
				AND E.TENANTID = v_idtenant
			INNER JOIN :TEMP_TRANSACTIONASSIGN T ON T.ORDERID = SO.ORDERID AND T.LINENUMBER = S.LINENUMBER  AND T.SUBLINENUMBER = S.SUBLINENUMBER AND T.EVENTTYPEID = E.EVENTTYPEID 
				AND T.POSITIONNAME = C.GENERICATTRIBUTE4 AND COALESCE(T.GENERICNUMBER2,0) <> 1 
				AND T.TENANTID = v_idtenant
			INNER JOIN EXT.OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST H ON H.POSITIONNAME = C.GENERICATTRIBUTE4
				AND H.CONTEO > 0 
				AND H.PERIODSEQ = v_periodseq
			WHERE C.PROCESSINGUNITSEQ = v_const_processingunitseq
			AND C.NAME = v_const_credito
			AND C.PERIODSEQ = v_periodseq 
			AND C.TENANTID = v_idtenant
			AND C.VALUE > 0 AND H.PERIODSEQ = v_periodseq
			ORDER BY C.GENERICATTRIBUTE4,C.VALUE DESC,RN;
		
		
			
		TEMP_NUEVO_CALCULO =
			SELECT C.GENERICATTRIBUTE4 POSITIONNAME,H.CONTEO,C.GENERICATTRIBUTE1 POLIZA,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID
			,SUM(C.PREADJUSTEDVALUE) SUMA
			,ROW_NUMBER() OVER (PARTITION BY C.GENERICATTRIBUTE4 ORDER BY SUM(C.PREADJUSTEDVALUE) DESC) AS RN
			-- , DENSE_RANK() OVER (PARTITION BY C.GENERICATTRIBUTE4 ORDER BY SUM(C.PREADJUSTEDVALUE) DESC) AS RN
			FROM CS_CREDIT C
			INNER JOIN CS_SALESTRANSACTION S ON C.SALESTRANSACTIONSEQ = S.SALESTRANSACTIONSEQ AND C.SALESORDERSEQ = S.SALESORDERSEQ AND S.PROCESSINGUNITSEQ = v_const_processingunitseq
				AND S.TENANTID = v_idtenant AND S.GENERICATTRIBUTE20 = 0
			INNER JOIN CS_SALESORDER SO ON SO.SALESORDERSEQ = S.SALESORDERSEQ AND REMOVEDATE = '2200-01-01' AND SO.PROCESSINGUNITSEQ = v_const_processingunitseq
				AND SO.TENANTID = v_idtenant
			INNER JOIN CS_EVENTTYPE E ON E.DATATYPESEQ = S.EVENTTYPESEQ AND E.REMOVEDATE =  '2200-01-01' AND E.EVENTTYPEID IN ('71','65')
				AND E.TENANTID = v_idtenant
			INNER JOIN :TEMP_TRANSACTIONASSIGN T ON T.ORDERID = SO.ORDERID AND T.LINENUMBER = S.LINENUMBER  AND T.SUBLINENUMBER = S.SUBLINENUMBER AND T.EVENTTYPEID = E.EVENTTYPEID 
				AND T.POSITIONNAME = C.GENERICATTRIBUTE4 AND COALESCE(T.GENERICNUMBER2,0) <> 1 
				AND T.TENANTID = v_idtenant
			INNER JOIN EXT.OUT_PAC_MARCADO_EXTORNO_S5_FILE_HIST H ON H.POSITIONNAME = C.GENERICATTRIBUTE4
				AND H.CONTEO > 0 AND H.PERIODSEQ = v_periodseq
			WHERE 1=1
			AND C.PROCESSINGUNITSEQ = v_const_processingunitseq
			AND C.NAME = v_const_credito
			AND C.PERIODSEQ = v_periodseq 
			AND C.TENANTID = v_idtenant
			AND C.VALUE > 0
			GROUP BY C.GENERICATTRIBUTE4,H.CONTEO,C.GENERICATTRIBUTE1,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID,T.GENERICDATE1
			ORDER BY SUMA DESC;
		
		SELECT 'TEMP_NUEVO_CALCULO',* FROM :TEMP_NUEVO_CALCULO WHERE POSITIONNAME = '29194073N0000' ORDER BY RN;
	
		TEMP_MAX_RN = SELECT
		            POSITIONNAME,
		            MAX(RN) AS MAX_RN
		        FROM :TEMP_NUEVO_CALCULO
		        GROUP BY POSITIONNAME;
		
		 
		
		
		-- UPDATE T
		-- SET T.GENERICNUMBER2 = (CASE WHEN (MR.MAX_RN-C.CONTEO) >= C.RN  THEN 0 ELSE 1 END)
		-- FROM EXT.TRANSACTIONASSIGN T 
		-- INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
		-- 	AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID AND T.POSITIONNAME = C.POSITIONNAME
		-- INNER JOIN :TEMP_MAX_RN MR ON MR.POSITIONNAME = C.POSITIONNAME
		-- INNER JOIN :TEMP_CREDITOS CR ON CR.POLIZA = C.POLIZA AND CR.LINENUMBER = T.LINENUMBER AND CR.SUBLINENUMBER = T.SUBLINENUMBER AND CR.EVENTTYPEID = T.EVENTTYPEID
		-- 	AND CR.POSITIONNAME = C.POSITIONNAME AND CR.ORDERID = T.ORDERID
		-- WHERE COALESCE(T.GENERICNUMBER2,0) <> 1;
		
		UPDATE T
		SET T.GENERICNUMBER2 = (CASE WHEN (MR.MAX_RN-C.CONTEO) >= C.RN  THEN 0 ELSE 1 END)
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID AND T.POSITIONNAME = C.POSITIONNAME
		INNER JOIN :TEMP_MAX_RN MR ON MR.POSITIONNAME = C.POSITIONNAME
		INNER JOIN :TEMP_CREDITOS CR ON CR.POLIZA = C.POLIZA AND CR.LINENUMBER = T.LINENUMBER AND CR.SUBLINENUMBER = T.SUBLINENUMBER AND CR.EVENTTYPEID = T.EVENTTYPEID
			AND CR.POSITIONNAME = C.POSITIONNAME AND CR.ORDERID = T.ORDERID
		WHERE COALESCE(T.GENERICNUMBER2,0) <> 1;
		
		DELETE FROM EXT.MARCADO_TRANSACTIONASSIGN_HIST WHERE BATCHNAME = i_file_name;
		
		INSERT INTO EXT.MARCADO_TRANSACTIONASSIGN_HIST(ORDERID,POLIZA,LINENUMBER,SUBLINENUMBER,EVENTTYPEID,POSITIONNAME,KM,SUMA,RN,CONTEO,MAX_RN,TENANTID,BATCHNAME,CREATEDATE)
		SELECT T.ORDERID,SUBSTRING(C.POLIZA,0,16) poliza,T.LINENUMBER,T.SUBLINENUMBER,T.EVENTTYPEID,T.POSITIONNAME,T.GENERICNUMBER2 KM,
		C.SUMA 
		,C.RN,C.CONTEO,R.MAX_RN
		,TENANTID,i_file_name,CURRENT_DATE
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID AND T.POSITIONNAME = C.POSITIONNAME
		INNER JOIN :TEMP_MAX_RN R ON R.POSITIONNAME = C.POSITIONNAME
		INNER JOIN :TEMP_CREDITOS CR ON CR.POLIZA = C.POLIZA AND CR.LINENUMBER = T.LINENUMBER AND CR.SUBLINENUMBER = T.SUBLINENUMBER AND CR.EVENTTYPEID = T.EVENTTYPEID
			AND CR.POSITIONNAME = C.POSITIONNAME AND CR.ORDERID = T.ORDERID
		-- WHERE T.POSITIONNAME = v_positionname
		ORDER BY POSITIONNAME,C.CONTEO DESC,T.POSITIONNAME, C.RN;


SELECT 'FINAL',T.ORDERID,SUBSTRING(C.POLIZA,0,16) poliza,T.LINENUMBER,T.SUBLINENUMBER,T.EVENTTYPEID,T.POSITIONNAME,T.GENERICNUMBER2 KM,
		C.SUMA 
		,C.RN,C.CONTEO,R.MAX_RN
		,TENANTID,i_file_name,CURRENT_DATE
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID AND T.POSITIONNAME = C.POSITIONNAME
		INNER JOIN :TEMP_MAX_RN R ON R.POSITIONNAME = C.POSITIONNAME
		INNER JOIN :TEMP_CREDITOS CR ON CR.POLIZA = C.POLIZA AND CR.LINENUMBER = T.LINENUMBER AND CR.SUBLINENUMBER = T.SUBLINENUMBER AND CR.EVENTTYPEID = T.EVENTTYPEID
			AND CR.POSITIONNAME = C.POSITIONNAME AND CR.ORDERID = T.ORDERID
		 --WHERE T.POSITIONNAME = '29194073N0000'
		ORDER BY POSITIONNAME,C.CONTEO DESC,T.POSITIONNAME, C.RN;
		
		
		UPDATE EXT.IN_BATCH_CONTROL
		SET STATUS = :v_const_out_batch_control_ok, 
			SOURCE_ROWS = v_num_rows,
			REJECTED_ROWS = 0,
			END_DATE = CURRENT_TIMESTAMP
		WHERE FILE_NAME = :i_file_name
		AND ID_PROCESO = v_id_proceso
		;
		
		CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log,proc_name, 'Fin procesamiento del fichero ' || i_file_name, v_log_count, v_id_proceso, 'info');
		
		
		
	END;
		
END;

DO BEGIN
	DECLARE v_file_name VARCHAR(250) = 'CONTEO_PACREQ1_20260422_130307.txt';
	DECLARE PLRUNSEQ BIGINT = 20547673299945597;
	
	
	DELETE FROM EXT.CSE_LOG WHERE CAST(DATETIME AS DATE) = CURRENT_DATE
	AND OBJECT LIKE '%SP_PAC_MARCADO_EXTORNO_S5%';
	
	CALL EXT.SP_PAC_MARCADO_EXTORNO_S5_TEST(v_file_name);
	
	SELECT * FROM EXT.CSE_LOG WHERE CAST(DATETIME AS DATE) = CURRENT_DATE
	AND OBJECT LIKE '%SP_PAC_MARCADO_EXTORNO_S5%';
	
	-- SELECT * FROM EXT.IN_BATCH_CONTROL WHERE CAST(START_DATE AS DATE) = CURRENT_DATE;
	
	SELECT * FROM EXT.MARCADO_TRANSACTIONASSIGN_HIST WHERE POSITIONNAME = '29194073N0000';

END;