CREATE OR REPLACE PROCEDURE EXT.SP_PAC_CONTEO_REQ2_INICIAL (IN i_file_name varchar(120))
LANGUAGE SQLSCRIPT 
SQL SECURITY INVOKER 
DEFAULT SCHEMA EXT AS

/*---------------------------------------------------------------------
    | Author: Samuel Miralles Manresa
    | Company: Inycom
    | Initial Version Date: 17/04/2026
    |----------------------------------------------------------------------
    | Procedure Purpose: Por cada póliza que aparezca en el fichero y el número de transacciones a marcar que se informará en el fichero
    |
    | Version: 0.1  SMM 20260331    Initial Version.
    |
    -----------------------------------------------------------------------
*/

BEGIN
	
	USING SQLSCRIPT_STRING AS LIBRARY;
	
	DECLARE v_id_proceso INTEGER;
	DECLARE proc_name VARCHAR2(50) := ::CURRENT_OBJECT_SCHEMA ||'.'|| ::CURRENT_OBJECT_NAME;
	DECLARE v_version VARCHAR2(10) := '0.1';
	DECLARE v_num_rows INTEGER := 0;
	DECLARE v_log_count INTEGER := 0;
	DECLARE v_permisos_log VARCHAR(50) := EXT.LIB_GLOBAL:GET_PERMISOS_LOG();
	DECLARE v_idtenant VARCHAR(50) := EXT.LIB_GLOBAL:getTenantID();
	DECLARE v_eot DATE := EXT.LIB_CONSTANTES:v_eot;
	DECLARE v_periodseq BIGINT;
	DECLARE v_PeriodName VARCHAR(25);
	DECLARE v_file_name VARCHAR(250) = 'PAC_CONTEO_REQ2_';
	DECLARE v_const_processingunitseq BIGINT = 38280596832649217;
	DECLARE v_const_credito VARCHAR(50) = 'DC-O-GEN-Inspector-PrimaCorregida-998';
	DECLARE v_const_medida VARCHAR(50) = 'SM-O-GEN-Inspector-NumeroPolizas-998-Extornar-S5';
	DECLARE v_const_out_batch_control_load INT = EXT.LIB_CONSTANTES:CONST_OUT_BATCH_CONTROL_LOAD; --1
	DECLARE v_const_out_batch_control_ok INT := EXT.LIB_CONSTANTES:CONST_OUT_BATCH_CONTROL_OK; --2
	DECLARE v_const_out_batch_control_error INT := EXT.LIB_CONSTANTES:CONST_OUT_BATCH_CONTROL_ERROR; --3

	DECLARE TEMP_CREDITOS_ORDENADOS TABLE (
		POLIZA VARCHAR(250),
		TOTAL DECIMAL(25,2),
		ORDEN INT,
		KM INT
	);
	
	DECLARE TEMP_TRANSACTIONASSIGN TABLE(
	"TENANTID" VARCHAR(4),
	"STAGESALESTRANSACTIONSEQ" BIGINT ,
	"SETNUMBER" BIGINT  NOT NULL,
	"BATCHNAME" VARCHAR(90) NOT NULL,
	"FILE_IN_RECIBOS" VARCHAR(90),
	"ORDERID" VARCHAR(40),
	"LINENUMBER" BIGINT ,
	"SUBLINENUMBER" BIGINT ,
	"EVENTTYPEID" VARCHAR(40),
	"SALESTRANSACTIONSEQ" BIGINT ,
	"PAYEEID" VARCHAR(40),
	"PAYEETYPE" VARCHAR(40),
	"POSITIONNAME" VARCHAR(127),
	"TITLENAME" VARCHAR(127),
	"GENERICATTRIBUTE1" VARCHAR(255),
	"GENERICATTRIBUTE2" VARCHAR(255),
	"GENERICATTRIBUTE3" VARCHAR(255),
	"GENERICATTRIBUTE4" VARCHAR(255),
	"GENERICATTRIBUTE5" VARCHAR(255),
	"GENERICATTRIBUTE6" VARCHAR(255),
	"GENERICATTRIBUTE7" VARCHAR(255),
	"GENERICATTRIBUTE8" VARCHAR(255),
	"GENERICATTRIBUTE9" VARCHAR(255),
	"GENERICATTRIBUTE10" VARCHAR(255),
	"GENERICATTRIBUTE11" VARCHAR(255),
	"GENERICATTRIBUTE12" VARCHAR(255),
	"GENERICATTRIBUTE13" VARCHAR(255),
	"GENERICATTRIBUTE14" VARCHAR(255),
	"GENERICATTRIBUTE15" VARCHAR(255),
	"GENERICATTRIBUTE16" VARCHAR(255),
	"GENERICNUMBER1" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER1" VARCHAR(40),
	"GENERICNUMBER2" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER2" VARCHAR(40),
	"GENERICNUMBER3" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER3" VARCHAR(40),
	"GENERICNUMBER4" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER4" VARCHAR(40),
	"GENERICNUMBER5" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER5" VARCHAR(40),
	"GENERICNUMBER6" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER6" VARCHAR(40),
	"GENERICDATE1" LONGDATE ,
	"GENERICDATE2" LONGDATE ,
	"GENERICDATE3" LONGDATE ,
	"GENERICDATE4" LONGDATE ,
	"GENERICDATE5" LONGDATE ,
	"GENERICDATE6" LONGDATE ,
	"GENERICBOOLEAN1" SMALLINT ,
	"GENERICBOOLEAN2" SMALLINT ,
	"GENERICBOOLEAN3" SMALLINT ,
	"GENERICBOOLEAN4" SMALLINT ,
	"GENERICBOOLEAN5" SMALLINT ,
	"GENERICBOOLEAN6" SMALLINT 
);

DECLARE TEMP_TRANSACTIONASSIGN_V2 TABLE(
	"TENANTID" VARCHAR(4),
	"STAGESALESTRANSACTIONSEQ" BIGINT ,
	"SETNUMBER" BIGINT  NOT NULL,
	"BATCHNAME" VARCHAR(90) NOT NULL,
	"FILE_IN_RECIBOS" VARCHAR(90),
	"ORDERID" VARCHAR(40),
	"LINENUMBER" BIGINT ,
	"SUBLINENUMBER" BIGINT ,
	"EVENTTYPEID" VARCHAR(40),
	"SALESTRANSACTIONSEQ" BIGINT ,
	"PAYEEID" VARCHAR(40),
	"PAYEETYPE" VARCHAR(40),
	"POSITIONNAME" VARCHAR(127),
	"TITLENAME" VARCHAR(127),
	"GENERICATTRIBUTE1" VARCHAR(255),
	"GENERICATTRIBUTE2" VARCHAR(255),
	"GENERICATTRIBUTE3" VARCHAR(255),
	"GENERICATTRIBUTE4" VARCHAR(255),
	"GENERICATTRIBUTE5" VARCHAR(255),
	"GENERICATTRIBUTE6" VARCHAR(255),
	"GENERICATTRIBUTE7" VARCHAR(255),
	"GENERICATTRIBUTE8" VARCHAR(255),
	"GENERICATTRIBUTE9" VARCHAR(255),
	"GENERICATTRIBUTE10" VARCHAR(255),
	"GENERICATTRIBUTE11" VARCHAR(255),
	"GENERICATTRIBUTE12" VARCHAR(255),
	"GENERICATTRIBUTE13" VARCHAR(255),
	"GENERICATTRIBUTE14" VARCHAR(255),
	"GENERICATTRIBUTE15" VARCHAR(255),
	"GENERICATTRIBUTE16" VARCHAR(255),
	"GENERICNUMBER1" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER1" VARCHAR(40),
	"GENERICNUMBER2" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER2" VARCHAR(40),
	"GENERICNUMBER3" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER3" VARCHAR(40),
	"GENERICNUMBER4" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER4" VARCHAR(40),
	"GENERICNUMBER5" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER5" VARCHAR(40),
	"GENERICNUMBER6" DECIMAL(25, 10) ,
	"UNITTYPEFORGENERICNUMBER6" VARCHAR(40),
	"GENERICDATE1" LONGDATE ,
	"GENERICDATE2" LONGDATE ,
	"GENERICDATE3" LONGDATE ,
	"GENERICDATE4" LONGDATE ,
	"GENERICDATE5" LONGDATE ,
	"GENERICDATE6" LONGDATE ,
	"GENERICBOOLEAN1" SMALLINT ,
	"GENERICBOOLEAN2" SMALLINT ,
	"GENERICBOOLEAN3" SMALLINT ,
	"GENERICBOOLEAN4" SMALLINT ,
	"GENERICBOOLEAN5" SMALLINT ,
	"GENERICBOOLEAN6" SMALLINT 
);
	
	BEGIN
	
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name , 'Error en procedimiento principal ' || proc_name || ' - SQL_ERROR_MESSAGE: ' || IFNULL(::SQL_ERROR_MESSAGE,'')
																												|| '. SQL_ERROR_CODE: ' || ::SQL_ERROR_CODE, v_log_count, v_id_proceso, 'error');
			--v_hayError := 1;
			v_num_rows := 0;
		
		UPDATE EXT.OUT_BATCH_CONTROL
		SET STATUS = v_const_out_batch_control_error,
			END_DATE = CURRENT_TIMESTAMP
		WHERE COALESCE(FILE_NAME,'') = COALESCE(v_file_name,'')
			AND ID_PROCESO = v_id_proceso;
			
			COMMIT;
			
			RESIGNAL;
		END;
	
	--Inicializamos el idProceso
		-- SELECT EXT.ID_PROCESO.NEXTVAL INTO v_id_proceso FROM DUMMY;
		SELECT 0 INTO v_id_proceso FROM DUMMY;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Version: ' || v_version || ' - Procedure starting for filename ' || i_file_name, v_log_count, v_id_proceso, 'info');
	
		
		-- SELECCIONAMOS PERIODSEQ
		-- SELECT PERIODSEQ, NAME INTO v_PeriodSeq, v_PeriodName FROM EXT.LIB_GLOBAL:getPeriodRow(v_idTenant, i_pPlRunSeq);
		
		-- FICHERO DE SALIDA
		-- SELECT v_file_name||TO_VARCHAR(CURRENT_DATE, 'YYYYMMDD')||'_'||TO_VARCHAR(ADD_SECONDS(CURRENT_TIME, 7200), 'HH24MISS')||'.txt' INTO v_file_name from dummy;
		
		
		/******************TEST****************************/
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TEST - CARGAMOS DATOS TRANSACTIONASSIGN: ', v_log_count, v_id_proceso, 'info');
		INSERT INTO :TEMP_TRANSACTIONASSIGN
		SELECT * FROM EXT.TRANSACTIONASSIGN 
		WHERE EVENTTYPEID IN ('71','65')
		-- AND POSITIONNAME = '70341664M0000' 
		AND LINENUMBER = 202604;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TEST - CARGAMOS DATOS TRANSACTIONASSIGN: FILAS ' || ::ROWCOUNT, v_log_count, v_id_proceso, 'info');
		
	
		
		-- SELECT 'TEMP_TRANSACTIONASSIGN',* FROM :TEMP_TRANSACTIONASSIGN WHERE POSITIONNAME = '70341664M0000' 
		-- AND ORDERID = '01501243602465000000000N23378'
		-- ORDER BY 3
		-- -- AND ORDERID LIKE '%3602465%'
		-- ;
		-- 01501243602465000000000N23378
		/*************************************************************/
	
		INSERT INTO EXT.OUT_BATCH_CONTROL(ID_PROCESO,FILE_NAME,PROCEDURE_NAME,TARGET_ROWS,STATUS,START_DATE,END_DATE)
		VALUES (v_id_proceso, v_file_name, ::CURRENT_OBJECT_NAME, v_num_rows, :v_const_out_batch_control_load, CURRENT_TIMESTAMP,NULL);
		
		SELECT TOP  1 L.PERIODSEQ, C.NAME INTO v_periodseq, v_PeriodName 
		FROM EXT.OUT_PAC_CONTEO_REQ2_FILE_LOAD L 
		INNER JOIN CS_PERIOD C ON L.PERIODSEQ = C.PERIODSEQ;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Parametros: v_PeriodSeq: ' || v_PeriodSeq || ' - v_PeriodName: ' || v_PeriodName, v_log_count, v_id_proceso, 'info');
		
		-- CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Eliminamos periodo en la tabla OUT_PAC_CONTEO_REQ2_FILE_HIST', v_log_count, v_id_proceso, 'info');
		DELETE FROM EXT.OUT_PAC_CONTEO_REQ2_FILE_HIST WHERE PERIODSEQ = v_periodseq;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Eliminamos periodo en la tabla OUT_PAC_CONTEO_REQ2_FILE_HIST. Filas: ' || ::ROWCOUNT, v_log_count, v_id_proceso, 'info');
		
		-- CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Cargamos periodo en la tabla OUT_PAC_CONTEO_REQ2_FILE_HIST', v_log_count, v_id_proceso, 'info');
		INSERT INTO EXT.OUT_PAC_CONTEO_REQ2_FILE_HIST(PERIODSEQ,POSITIONNAME,CONTEO,BATCHNAME,CREATEDATE)
		SELECT PERIODSEQ,POSITIONNAME,CONTEO,i_file_name,CURRENT_TIMESTAMP FROM EXT.OUT_PAC_CONTEO_REQ2_FILE_LOAD; 
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'Cargamos periodo en la tabla OUT_PAC_CONTEO_REQ2_FILE_HIST. Filas: ' || ::ROWCOUNT, v_log_count, v_id_proceso, 'info');
		
		
		SELECT 'OUT_PAC_CONTEO_REQ2_FILE_HIST',* FROM EXT.OUT_PAC_CONTEO_REQ2_FILE_HIST ORDER BY CONTEO DESC;
		
		
	
		
		SELECT 'QUERY-1',C.GENERICATTRIBUTE4,H.CONTEO,SO.ORDERID,C.GENERICATTRIBUTE1 POLIZA,substring(C.GENERICATTRIBUTE1,0,15) np,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID,C.NAME,C.ORIGINTYPEID,C.PREADJUSTEDVALUE,C.GENERICATTRIBUTE2 
		FROM CS_CREDIT C
		INNER JOIN CS_SALESTRANSACTION S ON C.SALESTRANSACTIONSEQ = S.SALESTRANSACTIONSEQ AND C.SALESORDERSEQ = S.SALESORDERSEQ AND S.PROCESSINGUNITSEQ = v_const_processingunitseq
		INNER JOIN CS_SALESORDER SO ON SO.SALESORDERSEQ = S.SALESORDERSEQ AND REMOVEDATE = '2200-01-01' AND SO.PROCESSINGUNITSEQ = v_const_processingunitseq
		INNER JOIN CS_EVENTTYPE E ON E.DATATYPESEQ = S.EVENTTYPESEQ AND E.REMOVEDATE =  '2200-01-01' AND EVENTTYPEID IN ('71','65')
		INNER JOIN EXT.OUT_PAC_CONTEO_REQ2_FILE_HIST H ON H.POSITIONNAME = C.GENERICATTRIBUTE4 
			AND H.CONTEO > 0
		WHERE 1=1
		AND C.PROCESSINGUNITSEQ = v_const_processingunitseq
		AND C.NAME = 'DC-O-GEN-Inspector-PrimaCorregida-998'
		-- AND C.GENERICATTRIBUTE4 = '70341664M0000'
		AND C.PERIODSEQ = v_periodseq 
		AND C.VALUE > 0
		-- AND C.GENERICATTRIBUTE1 = '000042784650000000000'
		ORDER BY H.CONTEO DESC;

		TEMP_NUEVO_CALCULO =
			SELECT C.GENERICATTRIBUTE4 POSITIONNAME,H.CONTEO,C.GENERICATTRIBUTE1 POLIZA,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID
			,SUM(C.PREADJUSTEDVALUE) SUMA
			,ROW_NUMBER() OVER (PARTITION BY C.GENERICATTRIBUTE4 ORDER BY SUM(C.PREADJUSTEDVALUE) DESC) AS RN
			FROM CS_CREDIT C
			INNER JOIN CS_SALESTRANSACTION S ON C.SALESTRANSACTIONSEQ = S.SALESTRANSACTIONSEQ AND C.SALESORDERSEQ = S.SALESORDERSEQ AND S.PROCESSINGUNITSEQ = v_const_processingunitseq
			INNER JOIN CS_SALESORDER SO ON SO.SALESORDERSEQ = S.SALESORDERSEQ AND REMOVEDATE = '2200-01-01' AND SO.PROCESSINGUNITSEQ = v_const_processingunitseq
			INNER JOIN CS_EVENTTYPE E ON E.DATATYPESEQ = S.EVENTTYPESEQ AND E.REMOVEDATE =  '2200-01-01' AND EVENTTYPEID IN ('71','65')
			INNER JOIN EXT.OUT_PAC_CONTEO_REQ2_FILE_HIST H ON H.POSITIONNAME = C.GENERICATTRIBUTE4
				AND H.CONTEO > 0
			WHERE 1=1
			AND C.PROCESSINGUNITSEQ = v_const_processingunitseq
			AND C.NAME = 'DC-O-GEN-Inspector-PrimaCorregida-998'
			-- AND C.GENERICATTRIBUTE4 = '70341664M0000'
			AND C.PERIODSEQ = v_periodseq 
			AND C.VALUE > 0
			-- AND C.GENERICATTRIBUTE1 = '000042784650000000000'
			GROUP BY C.GENERICATTRIBUTE4,H.CONTEO,C.GENERICATTRIBUTE1,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID
			ORDER BY 2 DESC;
		
		
		
			
			
		SELECT 'TEMP_NUEVO_CALCULO',* FROM :TEMP_NUEVO_CALCULO WHERE POSITIONNAME = '70341664M0000' ORDER BY suma desc;
		
		
		SELECT 'FINAL',*
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON 1=1 
		AND T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
		AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		WHERE C.POSITIONNAME = '70341664M0000'
		ORDER BY C.RN DESC
		;
		
	
		TEMP_MAX_RN = SELECT
		            POSITIONNAME,
		            MAX(RN) AS MAX_RN
		        FROM :TEMP_NUEVO_CALCULO
		        GROUP BY POSITIONNAME;
		
		 SELECT * FROM :TEMP_MAX_RN;
		
		
		UPDATE T
		SET T.GENERICNUMBER2 = (CASE WHEN (MR.MAX_RN-C.CONTEO) >= C.RN THEN 0 ELSE 1 END)
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		INNER JOIN :TEMP_MAX_RN MR ON MR.POSITIONNAME = C.POSITIONNAME
		;
		
		


		
		SELECT 'FINAL-FINAL',T.ORDERID,SUBSTRING(C.POLIZA,0,16),T.LINENUMBER,T.SUBLINENUMBER,T.EVENTTYPEID,T.POSITIONNAME,T.GENERICNUMBER2,
		C.SUMA 
		,C.RN,C.CONTEO,R.MAX_RN
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		INNER JOIN :TEMP_MAX_RN R ON R.POSITIONNAME = C.POSITIONNAME
		ORDER BY C.CONTEO DESC,T.POSITIONNAME, C.RN 
		;
		
		SELECT '***FINAL-FINAL',T.*
		,T.LINENUMBER,T.SUBLINENUMBER,T.EVENTTYPEID,T.POSITIONNAME,T.GENERICNUMBER2,
		C.SUMA 
		,C.RN,C.CONTEO,R.MAX_RN
		FROM :TEMP_TRANSACTIONASSIGN T 
		INNER JOIN :TEMP_NUEVO_CALCULO C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		INNER JOIN :TEMP_MAX_RN R ON R.POSITIONNAME = C.POSITIONNAME
		WHERE T.POSITIONNAME = '70341664M0000'
		ORDER BY C.CONTEO DESC,T.POSITIONNAME, C.RN 
		-- ORDER BY 3
		
		;
		
		UPDATE EXT.OUT_BATCH_CONTROL SET STATUS = :v_const_out_batch_control_ok, TARGET_ROWS =v_num_rows, END_DATE = CURRENT_TIMESTAMP WHERE FILE_NAME = v_file_name AND ID_PROCESO = v_id_proceso;
		
		CALL EXT.LIB_GLOBAL:WRITE_LOG (v_permisos_log,proc_name, 'Fin procesamiento del fichero ' || i_file_name, v_log_count, v_id_proceso, 'info');
		
		/******************TEST****************************/
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TEST - CARGAMOS DATOS TRANSACTIONASSIGN: ', v_log_count, v_id_proceso, 'info');
		INSERT INTO :TEMP_TRANSACTIONASSIGN_V2
		SELECT * FROM EXT.TRANSACTIONASSIGN 
		WHERE EVENTTYPEID IN ('71','65')
		-- AND POSITIONNAME = '70341664M0000' 
		AND LINENUMBER = 202604;
		CALL LIB_GLOBAL:WRITE_LOG (v_permisos_log, proc_name, 'TEST - CARGAMOS DATOS TRANSACTIONASSIGN: FILAS ' || ::ROWCOUNT, v_log_count, v_id_proceso, 'info');
		
	
		UPDATE :TEMP_TRANSACTIONASSIGN_V2 SET GENERICNUMBER2 = 1 WHERE POSITIONNAME = '70341664M0000' 
		AND ORDERID IN ('01501243602465000000000N23378','01290230000426799000000 0276YY025FE86F5');
		
		SELECT 'TEMP_TRANSACTIONASSIGN_V2',* FROM :TEMP_TRANSACTIONASSIGN_V2 WHERE POSITIONNAME = '70341664M0000' 
		AND ORDERID IN ('01501243602465000000000N23378','01290230000426799000000 0276YY025FE86F5')
		ORDER BY 3
		-- AND ORDERID LIKE '%3602465%'
		;
		-- 01501243602465000000000N23378
		
		TEMP_NUEVO_CALCULO_V2 =
		SELECT  X.POSITIONNAME,X.CONTEO,X.POLIZA,X.LINENUMBER,X.SUBLINENUMBER,X.EVENTTYPEID
			,X.SUMA
			-- ,SUM(X.PREADJUSTEDVALUE) SUMA
			,DENSE_RANK() OVER (PARTITION BY X.POSITIONNAME ORDER BY (X.SUMA) DESC) AS RN
		FROM (
			SELECT C.GENERICATTRIBUTE4 POSITIONNAME,H.CONTEO,C.GENERICATTRIBUTE1 POLIZA,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID
			-- ,C.PREADJUSTEDVALUE
			,SUM(C.PREADJUSTEDVALUE) SUMA
			-- ,ROW_NUMBER() OVER (PARTITION BY C.GENERICATTRIBUTE4 ORDER BY SUM(C.PREADJUSTEDVALUE) DESC) AS RN
			FROM CS_CREDIT C
			INNER JOIN CS_SALESTRANSACTION S ON C.SALESTRANSACTIONSEQ = S.SALESTRANSACTIONSEQ AND C.SALESORDERSEQ = S.SALESORDERSEQ AND S.PROCESSINGUNITSEQ = v_const_processingunitseq
			INNER JOIN CS_SALESORDER SO ON SO.SALESORDERSEQ = S.SALESORDERSEQ AND REMOVEDATE = '2200-01-01' AND SO.PROCESSINGUNITSEQ = v_const_processingunitseq
			INNER JOIN CS_EVENTTYPE E ON E.DATATYPESEQ = S.EVENTTYPESEQ AND E.REMOVEDATE =  '2200-01-01' AND EVENTTYPEID IN ('71','65')
			INNER JOIN EXT.OUT_PAC_CONTEO_REQ2_FILE_HIST H ON H.POSITIONNAME = C.GENERICATTRIBUTE4
				AND H.CONTEO > 0
			WHERE 1=1
			AND C.PROCESSINGUNITSEQ = v_const_processingunitseq
			AND C.NAME = 'DC-O-GEN-Inspector-PrimaCorregida-998'
			AND C.PERIODSEQ = v_periodseq 
			AND C.VALUE > 0
			GROUP BY C.GENERICATTRIBUTE4,H.CONTEO,C.GENERICATTRIBUTE1,S.LINENUMBER,S.SUBLINENUMBER,E.EVENTTYPEID
		) X INNER JOIN :TEMP_TRANSACTIONASSIGN_V2 T  ON 1=1 
			AND T.ORDERID LIKE  '%'||SUBSTRING(X.POLIZA,0,16)||'%'
			-- AND T.ORDERID  = X.ORDERID
			AND T.LINENUMBER = X.LINENUMBER AND T.SUBLINENUMBER = X.SUBLINENUMBER AND T.EVENTTYPEID = X.EVENTTYPEID
			AND T.POSITIONNAME = X.POSITIONNAME
			-- AND T.POSITIONNAME = '70341664M0000'
			WHERE X.POSITIONNAME = '70341664M0000' AND COALESCE(T.GENERICNUMBER2,0) != 1
		 --GROUP BY X.POSITIONNAME,X.CONTEO,X.POLIZA,X.LINENUMBER,X.SUBLINENUMBER,X.EVENTTYPEID,X.PREADJUSTEDVALUE
		ORDER BY 2 DESC;
			
		SELECT 'TEMP_NUEVO_CALCULO_V2',* FROM :TEMP_NUEVO_CALCULO_V2 WHERE POSITIONNAME = '70341664M0000' ORDER BY RN;
		
		SELECT 'FINAL_V2',*
		FROM :TEMP_TRANSACTIONASSIGN_V2 T 
		INNER JOIN :TEMP_NUEVO_CALCULO_V2 C ON 1=1 
		AND T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
		AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		AND T.POSITIONNAME = '70341664M0000'
		ORDER BY C.RN DESC
		;
		
		TEMP_MAX_RN_V2 = SELECT
		            POSITIONNAME,
		            MAX(RN) AS MAX_RN
		        FROM :TEMP_NUEVO_CALCULO_V2
		        GROUP BY POSITIONNAME;
		
		 SELECT * FROM :TEMP_MAX_RN_V2;
		
		
		-- UPDATE T
		-- SET T.GENERICNUMBER2 = (CASE WHEN (MR.MAX_RN-C.CONTEO) >= C.RN THEN 0 ELSE 2 END)
		-- FROM :TEMP_TRANSACTIONASSIGN_V2 T 
		-- INNER JOIN :TEMP_NUEVO_CALCULO_V2 C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
		-- 	AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		-- INNER JOIN :TEMP_MAX_RN_v2 MR ON MR.POSITIONNAME = C.POSITIONNAME
		-- ;
		
		SELECT '***FINAL-FINAL_V2',T.*
		,T.LINENUMBER,T.SUBLINENUMBER,T.EVENTTYPEID,T.POSITIONNAME,T.GENERICNUMBER2
		,C.SUMA 
		,C.RN
		,C.CONTEO
		,C.POLIZA
		,R.MAX_RN
		FROM :TEMP_TRANSACTIONASSIGN_V2 T 
		LEFT JOIN :TEMP_NUEVO_CALCULO_V2 C ON T.ORDERID LIKE  '%'||SUBSTRING(C.POLIZA,0,16)||'%'
			AND T.LINENUMBER = C.LINENUMBER AND T.SUBLINENUMBER = C.SUBLINENUMBER AND T.EVENTTYPEID = C.EVENTTYPEID
		LEFT JOIN :TEMP_MAX_RN_V2 R ON R.POSITIONNAME = C.POSITIONNAME
		WHERE T.POSITIONNAME = '70341664M0000'
		AND T.ORDERID IN ('01501243602465000000000N23378','01290230000426799000000 0276YY025FE86F5')
		-- ORDER BY C.CONTEO DESC,T.POSITIONNAME, C.RN 
		-- ORDER BY 3
		
		;
		/*************************************************************/
		
	END;
		
END