CREATE VIEW "EXT"."VW_OUT_PAC_CONTEO_REQ1_FILE" ( LINEA ) AS (SELECT LINEA
	FROM (
		SELECT ORDERID||','||LINENUMBER||','||SUBLINENUMBER||','||EVENTTYPEID||','||CONTEO AS LINEA FROM EXT.OUT_PAC_CONTEO_REQ1_FILE 
		UNION ALL
		SELECT  NULL AS LINEA FROM DUMMY
	) ORDER BY
  CASE WHEN LINEA IS NULL THEN 1 ELSE 0 END, LINEA) WITH READ ONLY