CREATE COLUMN TABLE "EXT"."MARCADO_TRANSACTIONASSIGN_HIST"(
	"ORDERID" VARCHAR(40),
	"POLIZA" VARCHAR(40),
	"LINENUMBER" BIGINT CS_FIXED,
	"SUBLINENUMBER" BIGINT CS_FIXED,
	"EVENTTYPEID" VARCHAR(40),
	"POSITIONNAME" VARCHAR(127),
	"KM" INT,
	"SUMA" DECIMAL(25,10),
	"RN" INT,
	"CONTEO" INT,
	"MAX_RN" INT,
	"TENANTID" VARCHAR(4) ,
	"BATCHNAME" VARCHAR(90) ,
	"CREATEDATE" DATETIME
)
UNLOAD PRIORITY 5 AUTO MERGE;