CREATE COLUMN TABLE "EXT"."OUT_PAC_CONTEO_REQ2_FILE_HIST"(
	"ORDERID" VARCHAR(40),
	"LINENUMBER" BIGINT CS_FIXED,
	"SUBLINENUMBER" BIGINT CS_FIXED,
	"EVENTTYPEID" VARCHAR(40),
	"POLIZA" VARCHAR(25),
	"CONTEO" INTEGER CS_INT,
	"PERIODSEQ" BIGINT CS_FIXED,
	"BATCHNAME" VARCHAR(250),
	"CREATEDATE" TIMESTAMP
	
	
)
UNLOAD PRIORITY 5 AUTO MERGE;
