CREATE COLUMN TABLE "EXT"."OUT_PAC_CONTEO_REQ1_FILE"(
	"ORDERID" VARCHAR(40),
	"LINENUMBER" BIGINT,
	"SUBLINENUMBER" BIGINT,
	"EVENTTYPEID" VARCHAR(40),
	"POLIZA" VARCHAR(25),
	"CONTEO" INT,
	"PERIODSEQ" BIGINT
)
UNLOAD PRIORITY 5 AUTO MERGE;
